### ISSUE TITLE
[Bug] Color Recognizer

### ISSUE THREAD

**Issue by drinfernoo** [zewelor/ha_custom_components#1]
I've been checking out your post here: https://community.home-assistant.io/t/change-your-rgb-lights-color-according-to-spotify-album-background/94885. This integration seems ideal for me, as it means I wouldn't have to get AppDaemon running, as some other solutions require.

I've added `color_recognizer:` in my `configuration.yaml` and created both a sensor and automaion:
```yaml
# sensor
sensor:
  - platform: template
    sensors:
      spotify_content_id:
        value_template: "{{ state_attr('media_player.hedwig', 'media_content_id') }}"
        friendly_name: Spotify Content ID

# automation
- id: spotify_match_music
  alias: Spotify Match Music
  trigger:
  - platform: state
    entity_id: sensor.spotify_content_id
  condition:
  - condition: template
    value_template: '{{ states(''sensor.spotify_content_id'') != ''None'' }}'
  action:
  - delay: 00:00:02
  - service: color_recognizer.turn_light_to_recognized_color
    data_template:
      entity_id: light.living_room_lamp
      url: '{{ state_attr(''media_player.hedwig'', ''entity_picture'') }}'
      transition: 3
  mode: single
```
With `media_player.hedwig` being my Nvidia Shield. I've verified that when music is being played on it via Spotify, the `media_content_id` and `entity_picture` states are being updated (only via casting, but I think that's a separate issue 🤔).

Unfortunately, I can't quite get the script to actually *run* 😅 

I get this error whenever my automation runs:
```bash
2020-09-28 17:06:05 ERROR (MainThread) [homeassistant.components.automation.spotify_match_music] Spotify Match Music: Error executing script. Service not found for call_service at pos 2: Unable to find service color_recognizer/turn_light_to_recognized_color
2020-09-28 17:06:05 ERROR (MainThread) [homeassistant.components.automation.spotify_match_music] While executing automation automation.spotify_match_music
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 944, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 198, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 206, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1265, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service color_recognizer/turn_light_to_recognized_color
```
And investigating further, it appears I'm getting a **lot** of output regarding `numpy==1.16` being unavailable. Full log here: https://pastebin.com/WCerpbvS

Is this an easy fix? Am I overlooking something? Is this an issue with my system... that for some reason it doesn't have/can't install `numpy`?

**Comment by zewelor** [comment]
Hi

I'm not using it currently, and not used it for longer time. As far as I remember there was need to install numpy by hand, as it was removed some time from HA. I think I've done it using https://github.com/home-assistant/hassio-addons-development and addons custom_dep . Afaik this should work: https://community.home-assistant.io/t/change-your-rgb-lights-color-according-to-spotify-album-background/94885/29

**Comment by drinfernoo** [comment]
Hmm, I don't think I'm able to go that route, as I run Home Assistant Core in a container, rather than Supervisor.

I looked into adding  a `manifest.json`:
```yaml
{
  "domain": "color_recognizer",
  "name": "Color Recognizer",
  "documentation": "https://github.com/zewelor/ha_custom_components/tree/master/color_recognizer",
  "dependencies": [],
  "codeowners": ["@zewelor"],
  "requirements": ["numpy==1.16", "pillow", "scipy"]
}
```
and `services.yaml`:
```yaml
turn_light_to_recognized_color:
  description: Changes the specified lights to match a prominent color from the image specifed.
  fields:
    entity:
      description: entity_id of the light you wish to change.
      example: light.living_room
    url:
      description: URL of an image to use for color recognition.
      example: https://i.scdn.co/image/ab67616d00001e028692b52d4f1a5d072e095b28
```
And those... helped? I no longer get `numpy` errors on boot, but am still getting the `ServiceNotFound` error when I try to call `color_recognizer.turn_light_to_recognized_color`.

**Comment by drinfernoo** [comment]
I've actually gotten this working! By removing the `==1.16` from the `numpy` requirement in `manifest.json` (as shown above), my system was able to run the script (I have `1.19.2` available) successfully.

Closing this one since I got it working 👌

I've made a few changes, and have some ideas for enhancements... Would you be open to possible pull requests in the future?

**Comment by zewelor** [comment]
Great you got this working ! As for PR they are always welcome, since I'm not using this now, maybe would be better if you made new repo with this ? Would be probably faster to add stuff then.

**Comment by drinfernoo** [comment]
With your blessing, I may do that 😁

I'd especially like to see this be available in HACS, because it was trivial to get it working in the end, and creates a very nice effect 👍

Good work, and thanks 🙏

**Comment by drinfernoo** [comment]
@zewelor If you'd like to give it a shot, I haven't posted it anywhere yet, but here's this: https://github.com/drinfernoo/color_fx

**Comment by zewelor** [comment]
Looks great, thanks for info !
